import environ
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# env = environ.Env(DEBUG=(bool, False))
# DEBUG = env('DEBUG')
env = environ.Env()

environ.Env.read_env(BASE_DIR / '../sync/aux' / 'prod.env')
environ.Env.read_env(BASE_DIR / '../sync/aux_reuse' / 'any.env')

SECRET_KEY = env('DJANGO_SECRET_KEY')
ADMIN_PATH = env('DJANGO_ADMIN_PATH')
PROJECT_NAME = env('DJANGO_PROJECT_NAME')
ENV_NAME = env('DJANGO_ENV_NAME', default='prod')

if ENV_NAME == 'dev':
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1']
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / '../local/db' / 'dev.sqlite3',}}
    # FIXME AFTER TESTING
    ADMIN_HEADER_BG = 'pink'  # darker green
    # ADMIN_HEADER_BG = '#008c00'  # darker green
else:
    # FIXME
    ALLOWED_HOSTS = ['noyo.pythonanywhere.com']
    DATABASES = { 'default': env.db_url('DATABASE_URL'), }
    ADMIN_HEADER_BG = '#8c0000'  # darker red


# ------------------------------------------------------------------------------
#           `startproject` remaining boilerplate
# ------------------------------------------------------------------------------

"""
Django settings for ___ project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

# ALLOWED_HOSTS = []

# Application definition

# INSTALLED_APPS = [
BASE_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'd1_project.urls_root'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # MODIFIED
        # this will not work if you reuse settings as a PyPI package
        # it only works as a git submodule or subtree
        'DIRS': [
            BASE_DIR / 'd2_gsm' / 'templates',
        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
        
                # added
                'd2_gsm.context_reuse.general',
            ],
        },
    },
]

WSGI_APPLICATION = 'd2_gsm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
